### ISSUE TITLE
custom component name should be constrained explicitely

### ISSUE THREAD

**Issue by ZBMO** [writer/writer-framework#517]
Custom component names defined by the dev in custom_components/index.ts must contain the full original name of the component lower-case.

For example, A customized the Metric component called "customMetric", compiles but can't be dragged into the ComponentRenderer, whereas "custommetric" and "nonsensemetric" work fine. AFAIK the constraints for naming are not in the docs. video of the behavior from the invalid name is below

https://github.com/user-attachments/assets/4d9c69e6-5511-47be-90aa-d1f79447292e

**Comment by FabienArcellier** [comment]
I was able to reproduce this bug. I also have the impression that I no longer have access to custom components through the `npm run custom.dev` command.

**Comment by FabienArcellier** [comment]
The problem comes from the [DataTransfer](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/setData) protocol. Doing `setData` clears the case on the format.

![image](https://github.com/user-attachments/assets/0f466241-f1b1-41b8-81aa-96aebe38864c)

![image](https://github.com/user-attachments/assets/e5054d60-bb0a-4c41-bd9a-b785202648bd)

**Comment by FabienArcellier** [comment]
We decide to go on raising error if id in custom_components/index use other character than `[a-z]`

**Comment by FabienArcellier** [comment]
it's available in [release `0.8.1`](https://pypi.org/project/writer/)
